# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"

# This feature is coming soon to Diesel
#[migrations_directory]
#file = "db/migrations"