# See documentation:
# <doc/rocket-toml/>

[global]
template_dir = "www/templates/"
limits = { forms = 32768 }
# workers = [number of cpus * 2]
# secret_key = [randomly generated at launch]

[debug]
address = "0.0.0.0"
port = 8000
keep_alive = 5
log_level = "debug"

[release]
address = "1.1.1.1"
port = 80
keep_alive = 10
log_level = "critical"

### databases

# Example using sqlx and SQLite.
# The Rocket URL below must match the SQLite URL as set in the file `main.rs`.
[default.databases.demo_rust_rocket_sqlite]
url = "databases/demo_rust_rocket.sqlite"

# Example using Diesel and PostgreSQL.
# The Rocket URL below must match the Diesel URL as set in the file `.env`.
[default.databases.demo_rust_rocket_postgres]
url = "postgres://demo_rust_rocket:secret@localhost/demo_rust_rocket"
pool_size = 20
